# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  gpsviewer_ui:
    image: gpsviewer_ui
    #restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker/DockerfileUI
    ports:
      - $PORT_UI:80
  gpsviewer_api:
    image: gpsviewer_api
    #restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker/DockerfileAPI
    ports:
      - $PORT_API:8080
